### ISSUE TITLE
Create JSDOM unit tests

### ISSUE THREAD

**Issue by motiz88** [digital-detox/react-svg-use-external#1]
- [x] Test with Jest + JSDOM - started in #13
- [x] Report coverage and add README badge (e.g. codecov.io) - done in #13
- [ ] Attain full unit test coverage - done in #20
